l=chr(60);g=chr(62);c=l+'/div'+g;s=l+'div';p='{';q='};'

lines=[
"import React from 'react';",
"import { Link } from 'react-router-dom';",
"import { Zap, Linkedin, Twitter, Github, Mail } from 'lucide-react';",
"",
"export default function Footer() {",
"  const footerLinks = {",
"    Product: [{label:'Features',to:'/features'},{label:'Pricing',to:'/pricing'},{label:'API Docs',to:'#'}],",
"    Company: [{label:'About Us',to:'/about'},{label:'Careers',to:'#'},{label:'Contact',to:'/contact'}],",
"    Resources: [{label:'Blog',to:'#'},{label:'Help Center',to:'#'},{label:'Status',to:'#'}],",
"    Legal: [{label:'Privacy',to:'#'},{label:'Terms',to:'#'},{label:'GDPR',to:'#'}],",
"  };",
"",
"  return (",
l+"footer style={{background:'var(--bg-surface)',color:'var(--text-secondary)',borderTop:'1px solid var(--border-subtle)',paddingTop:'3rem'}}"+g,
"  "+l+"div className=\"container\" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:'2.5rem',paddingBottom:'2.5rem'}}"+g,
"    "+l+"div style={{minWidth:'200px'}}"+g,
"      "+l+"Link to=\"/\" style={{display:'flex',alignItems:'center',gap:'0.6rem',textDecoration:'none',marginBottom:'1rem'}}"+g,
"        "+l+"div style={{width:'30px',height:'30px',background:'var(--accent-gradient)',borderRadius:'8px',display:'flex',alignItems:'center',justifyContent:'center'}}"+g,
"          "+l+"Zap size={15} color=\"#fff\" strokeWidth={2.5} /"+g,
"        "+c,
"        "+l+"span style={{fontWeight:800,fontSize:'1.1rem',color:'#fff'}}"+g+"SmartHire"+l+"/span"+g,
"      "+l+"/Link"+g,
"      "+l+"p style={{fontSize:'0.85rem',lineHeight:1.6,color:'var(--text-muted)',maxWidth:'260px'}}"+g,
"        Recruitment software that parses resumes, scores matches, and helps you hire faster.",
"      "+l+"/p"+g,
"      "+l+"div className=\"flex\" style={{gap:'0.75rem',marginTop:'1.25rem'}}"+g,
"        "+l+"a href=\"#\" style={{color:'var(--text-muted)',transition:'var(--transition-fast)'}}"+g+l+"Linkedin size={18} /"+g+l+"/a"+g,
"        "+l+"a href=\"#\" style={{color:'var(--text-muted)',transition:'var(--transition-fast)'}}"+g+l+"Twitter size={18} /"+g+l+"/a"+g,
"        "+l+"a href=\"#\" style={{color:'var(--text-muted)',transition:'var(--transition-fast)'}}"+g+l+"Github size={18} /"+g+l+"/a"+g,
"        "+l+"a href=\"#\" style={{color:'var(--text-muted)',transition:'var(--transition-fast)'}}"+g+l+"Mail size={18} /"+g+l+"/a"+g,
"      "+c,
"    "+c,
"    {Object.entries(footerLinks).map(([category,links])=>"+l+"div key={category}"+g,
"      "+l+"h4 style={{color:'#fff',fontSize:'0.8rem',fontWeight:700,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:'1rem'}}"+g+"{category}"+l+"/h4"+g,
"      "+l+"ul style={{listStyle:'none',display:'flex',flexDirection:'column',gap:'0.6rem'}}"+g,
"        {links.map(link=>"+l+"li key={link.label}"+g,
"          "+l+"Link to={link.to} style={{color:'var(--text-muted)',textDecoration:'none',fontSize:'0.85rem',transition:'var(--transition-fast)'}}"+g+"{link.label}"+l+"/Link"+g,
"        "+l+"/li"+g+")}",
"      "+l+"/ul"+g,
"    "+c+")}",
"  "+c,
"  "+l+"div style={{borderTop:'1px solid var(--border-subtle)'}}"+g,
"    "+l+"div className=\"container flex-between\" style={{paddingTop:'1.5rem',paddingBottom:'1.5rem',flexWrap:'wrap',gap:'0.5rem'}}"+g,
"      "+l+"p style={{fontSize:'0.8rem',color:'var(--text-muted)'}}"+g+"&copy; {new Date().getFullYear()} SmartHire AI, Inc."+l+"/p"+g,
"      "+l+"p style={{fontSize:'0.8rem',color:'var(--text-muted)'}}"+g+"Built for modern talent teams."+l+"/p"+g,
"    "+c,
"  "+c,
l+"/footer"+g,
"  );",
"}",
];

with open('frontend/src/components/Footer.jsx','w') as f:
    for line in lines:
        f.write(line+'\n')
print('done')

